server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/backend_spring
#    username: postgres
#    password: root
    url: jdbc:postgresql://dpg-ctu03srqf0us73evrdpg-a.singapore-postgres.render.com:5432/backend_byspring
    username: backend_byspring_user
    password: 8snNbVWtBn5R8a2uMhnrtOSQ6zBsdrXI
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: xiaoming00009@gmail.com
    password: xmhrunotdhgbfjbb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  upload: upload/
base:
  url: http://localhost:8080



