spring:
  datasource:
    url: jdbc:postgresql://dpg-ctub0phopnds73ck9jag-a.singapore-postgres.render.com:5432/backendbyspring
    username: root
    password: LM9lj6zPW8PYrh094Q6Erq5gJwcOBGHV


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: xiaoming00009@gmail.com
    password: xmhrunotdhgbfjbb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  upload: upload/
base:
  url: http://dpg-ctub0phopnds73ck9jag-a



